#!/usr/bin/with-contenv bash

umask 022

  # python /app/couchpotato/CouchPotato.py \
  # --config_file=/config/config.ini --data_dir=/config/data

exec \
  s6-setuidgid abc /usr/bin/python2.7 /app/sickrage/SickBeard.py --config=/config/config.ini --datadir=/config/data   
